version: '3.8'

services:
  vectum:
    image: crpi-4pdi7kz96g4v0tg3.cn-beijing.personal.cr.aliyuncs.com/coolxer-studio/vectum:latest
    container_name: vectum
    ports:
      - "11002:11002"
    volumes:
      - ./workspace:/workspace
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
